#!/usr/bin/env bash

set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
deploy_dir="${DEPLOY_DIR:-"$repo_dir/../tuananhbui89.github.io"}"

if [[ ! -d "$deploy_dir/.git" ]]; then
  echo "Deployment repository not found at: $deploy_dir" >&2
  exit 1
fi

cd "$repo_dir"

# Start from an empty production destination so files generated by a previous
# draft preview cannot survive into this build.
bundle exec jekyll clean

# Production minification uses ExecJS. Force the installed Node.js runtime
# because the old mini_racer extension bundled with this project crashes under
# Apple's system Ruby 2.6 on current macOS versions.
if ! command -v node >/dev/null 2>&1; then
  echo "Node.js is required for the production Jekyll build." >&2
  exit 1
fi
EXECJS_RUNTIME=Node JEKYLL_ENV=production bundle exec jekyll build

# Mirror the generated site and remove pages that no longer exist. Preserve
# repository metadata and its local ignore rules.
rsync -av --progress --delete \
  --exclude='.git/' \
  --exclude='.gitignore' \
  _site/ "$deploy_dir/"

git -C "$deploy_dir" add -A

if git -C "$deploy_dir" diff --cached --quiet; then
  echo "No generated-site changes to publish."
  exit 0
fi

git -C "$deploy_dir" commit -m "update"
git -C "$deploy_dir" push
